# Generated by Django 3.2.7 on 2021-10-17 20:56

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='nombre usuario')),
                ('first_name', models.CharField(max_length=20, verbose_name='Nombre de usuario')),
                ('last_name', models.CharField(max_length=20, verbose_name='apellido del usuario')),
                ('cedula', models.CharField(max_length=10, verbose_name='cedula del usuario')),
                ('phone', models.CharField(max_length=10, verbose_name='Telefono del usuario')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Empresa', models.BooleanField(default=False, verbose_name='es empresa')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=30, verbose_name='region')),
                ('price', models.IntegerField(verbose_name='precio')),
                ('description', models.CharField(max_length=250, verbose_name='descripcion')),
                ('phone', models.CharField(max_length=10, verbose_name='telefono')),
            ],
            options={
                'verbose_name': 'alquiler',
                'verbose_name_plural': 'alquileres',
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(default=datetime.date(2021, 10, 17), verbose_name='fecha de inicio')),
                ('date_end', models.DateField(default=datetime.date(2021, 10, 17), verbose_name='fecha de fin')),
                ('transporte', models.CharField(choices=[('avion', 'Aereo'), ('bus', 'terrestre'), ('barco', 'maritimo')], max_length=32, verbose_name='medio de transporte')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('alquiler', 'alquiler'), ('restaurante', 'restaurante'), ('guia', 'guia')], max_length=30, verbose_name='tipo de servicio')),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alquiler', to='api.rental')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_de_viaje', to='api.travel')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='Rute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rute_name', models.CharField(max_length=30, verbose_name='nombre de la ruta turistica')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruta_de_viaje', to='api.travel')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
            },
        ),
        migrations.CreateModel(
            name='Destiny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre del destino')),
                ('vacations_type', models.CharField(choices=[('Aventura', 'aventura'), ('medicinal', 'medicinal'), ('aves y fauna', 'avistamiento'), ('empresarial', 'laboral')], max_length=32, verbose_name='tipo de destino')),
                ('image', models.ImageField(blank=True, upload_to='destiny')),
                ('region', models.CharField(choices=[('Amazonia', 'amazonas'), ('Andina', 'andina'), ('Caribe', 'caribe'), ('Pacifico', 'pacifico'), ('Orinoquia', 'orinoquia')], max_length=30, verbose_name='locacion')),
                ('price', models.IntegerField(verbose_name='precio')),
                ('rute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruta', to='api.rute')),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Titulo')),
                ('body', models.TextField(verbose_name='cuerpo del blog')),
                ('image', models.ImageField(upload_to='Blog', verbose_name='imagen opcional')),
                ('tag', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Viaje', 'Viaje'), ('aventura', 'aventura'), ('fauna', 'fauna'), ('paisaje cultural', 'paisaje'), ('exploraracion', 'explorar'), ('naturaleza', 'naturaleza'), ('comida', 'comida'), ('descubrir', 'descubrir')], max_length=79)),
                ('region', models.CharField(max_length=30, verbose_name='region')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada del blog',
            },
        ),
    ]
