# Generated by Django 3.2.7 on 2021-10-18 21:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211017_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destiny',
            name='rute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='api.rute'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='date_end',
            field=models.DateField(default=datetime.date(2021, 10, 18), verbose_name='fecha de fin'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 10, 18), verbose_name='fecha de inicio'),
        ),
    ]
