# Generated by Django 3.2.7 on 2021-10-19 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211018_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destiny',
            name='rute',
        ),
        migrations.AddField(
            model_name='destiny',
            name='rute',
            field=models.ManyToManyField(to='api.Rute'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='date_end',
            field=models.DateField(default=datetime.date(2021, 10, 19), verbose_name='fecha de fin'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 10, 19), verbose_name='fecha de inicio'),
        ),
    ]
