# Generated by Django 3.2.7 on 2021-10-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211019_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destiny',
            name='rute',
        ),
        migrations.AddField(
            model_name='rute',
            name='ruta_destinos',
            field=models.ManyToManyField(to='api.Destiny'),
        ),
    ]
