# Generated by Django 3.2.7 on 2021-12-03 23:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211021_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='date_end',
            field=models.DateField(default=datetime.date(2021, 12, 3), verbose_name='fecha de fin'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 12, 3), verbose_name='fecha de inicio'),
        ),
    ]
