# Generated by Django 3.2.7 on 2021-12-04 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211203_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destiny',
            name='nombre',
            field=models.CharField(max_length=80, verbose_name='Nombre del destino'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='date_end',
            field=models.DateField(default=datetime.date(2021, 12, 4), verbose_name='fecha de fin'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 12, 4), verbose_name='fecha de inicio'),
        ),
    ]
