# Generated by Django 3.2.7 on 2021-12-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211204_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='region',
            field=models.CharField(max_length=80, verbose_name='region'),
        ),
    ]
