# Generated by Django 3.2.7 on 2021-12-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_rental_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destiny',
            name='vacations_type',
            field=models.CharField(choices=[('Aventura', 'aventura'), ('medicinal', 'medicinal'), ('aves y fauna', 'avistamiento'), ('empresarial', 'laboral'), ('Diversion', 'Ocio,Diversion')], max_length=32, verbose_name='tipo de destino'),
        ),
    ]
